[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
]

[rpc_endpoints]
# bsc = "https://bsc-dataseed.bnbchain.org"
bsc = "https://bsc-testnet.bnbchain.org"
# base = "https://mainnet.base.org"
base = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

